name: daily_local_notifications
description: A Flutter Widget for setting daily local notifications.
version: 0.2.1+4
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: 3.13.8

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.1.0
  flutter_time_picker_spinner:
    git: https://github.com/novas1r1/flutter_time_picker_spinner.git
  flutter_timezone: ^1.0.8
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  very_good_analysis: ^5.1.0
